# Generated by Django 5.1.1 on 2024-09-11 05:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='item_image',
            field=models.CharField(default='https://cdni.iconscout.com/illustration/premium/thumb/server-down-of-restaurant-website-illustration-download-in-svg-png-gif-file-formats--404-error-not-found-page-food-delivery-pack-e-commerce-shopping-illustrations-3605234.png?f=webp', max_length=500),
        ),
    ]
